#!/usr/bin/env python3
"""Generate both RFC lifecycle indexes from canonical front matter (RFC 101)."""
import re
import sys
from pathlib import Path

ROOT = Path(".")
RFCS = ROOT / "rfcs"
BOOK_OUT = ROOT / "docs/src/generated/rfc-index.md"
ROOT_OUT = RFCS / "README.md"
HEADER = ("<!-- GENERATED by scripts/extract_rfc_index.py from RFC front matter. "
          "Do not edit by hand. -->\n")


def front_matter(path):
    m = re.match(r"---\n(.*?)\n---\n", path.read_text(), re.S)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            fm[key.strip()] = value.strip()
    return fm


def collect():
    rows = {"done": [], "proposed": [], "archive": []}
    for folder in rows:
        for path in sorted((RFCS / folder).glob("[0-9]*.md")):
            fm = front_matter(path)
            if fm:
                rows[folder].append({**fm, "filename": path.name})
        rows[folder].sort(key=lambda row: int(row["rfc"]))
    return rows


def summary(rows):
    total = sum(map(len, rows.values()))
    return (f"{total} RFCs: {len(rows['done'])} implemented, "
            f"{len(rows['proposed'])} proposed/in-wave, "
            f"{len(rows['archive'])} archived. Generated from RFC front matter.")


def render_book(rows):
    out = [HEADER, "# RFC index", "", summary(rows), ""]
    if rows["done"]:
        out += ["## Implemented (`done/`)", "",
                "| RFC | Title | Shipped | Category |", "|---|---|---|---|"]
        for r in rows["done"]:
            path = f"../../../rfcs/done/{r['filename']}"
            out.append(f"| [{r['rfc']}]({path}) | {r['title']} | "
                       f"{r['implemented_in']} | {r['category']} |")
        out.append("")
    if rows["proposed"]:
        out += ["## Proposed / in-wave (`proposed/`)", "",
                "| RFC | Title | Status | Category |", "|---|---|---|---|"]
        for r in rows["proposed"]:
            path = f"../../../rfcs/proposed/{r['filename']}"
            out.append(f"| [{r['rfc']}]({path}) | {r['title']} | "
                       f"{r['status']} | {r['category']} |")
        out.append("")
    if rows["archive"]:
        out += ["## Archived (`archive/`)", "",
                "| RFC | Title | Status | Note |", "|---|---|---|---|"]
        for r in rows["archive"]:
            path = f"../../../rfcs/archive/{r['filename']}"
            note = (f"superseded by RFC {r['superseded_by'].strip('[]')}"
                    if r["status"] == "Superseded" else r["status"])
            out.append(f"| [{r['rfc']}]({path}) | {r['title']} | "
                       f"{r['status']} | {note} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_root(rows):
    out = [HEADER, "# Henret RFC Index", "",
           "Lifecycle policy: [`RFC 000`](done/000-rfc-lifecycle-policy.md). "
           "New RFCs start from [`TEMPLATE.md`](TEMPLATE.md).",
           "The [project roadmap](../docs/src/roadmap.md) owns milestone order.",
           "", summary(rows), ""]
    specs = (("done", "Implemented", "Shipped"),
             ("proposed", "Proposed", "Depends on"),
             ("archive", "Archived", "Note"))
    for folder, heading, last in specs:
        out += [f"## {heading}", "", f"| RFC | Title | {last} | Category |",
                "|---|---|---|---|"]
        for r in rows[folder]:
            path = f"{folder}/{r['filename']}"
            if folder == "done":
                value = r["implemented_in"]
            elif folder == "proposed":
                value = r["depends_on"].strip("[]").strip() or "—"
            else:
                value = (f"superseded by RFC {r['superseded_by'].strip('[]')}"
                         if r["status"] == "Superseded" else r["status"])
            out.append(f"| [{int(r['rfc']):03d}]({path}) | {r['title']} | "
                       f"{value} | {r['category']} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    check = "--check" in sys.argv
    rows = collect()
    outputs = {BOOK_OUT: render_book(rows), ROOT_OUT: render_root(rows)}
    diverged = []
    for path, content in outputs.items():
        if check:
            if not path.exists() or path.read_text() != content:
                diverged.append(path.as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if diverged:
        print(f"GENERATED-DOC DIVERGENCE: {diverged} differ — run "
              "scripts/extract_rfc_index.py and commit")
        raise SystemExit(1)
    if check:
        print("rfc-index: both generated indexes match committed output")
    else:
        print(f"rfc-index: wrote {len(outputs)} generated indexes")


if __name__ == "__main__":
    main()
