#!/usr/bin/env python3
"""RFC 084 — model-documentation generator (Model import cost, 084-5).

Reads the checked descriptor source `Henret/Meta/Docs.lean`, validates each
list against the real Lean declarations (every name resolves to an actual
constructor/field, names are duplicate-free, the metadata count equals the
real count — 084-1), and emits the operation / state / result / WellFormed
tables to `docs/src/generated/`.

    extract_model_docs.py            # write docs/src/generated/*.md
    extract_model_docs.py --check    # regenerate and diff committed files

Stdlib only. The theorem index and axiom budget are generated separately
(`extract_theorem_docs.py`) so these cheap tables never force a proof build.
"""
import re
import sys
from pathlib import Path

ROOT = Path(".")
META = ROOT / "Henret/Meta/Docs.lean"
OUT = ROOT / "docs/src/generated"

SOURCES = {
    "runtimeOpDocs":  ("ctor",  "Henret/Scheduler/Op.lean",   "RuntimeOp"),
    "taskStateDocs":  ("ctor",  "Henret/Actor/Task.lean",     "TaskState"),
    "stepResultDocs": ("ctor",  "Henret/Core/Result.lean",    "StepResult"),
    "wellFormedDocs": ("field", "Henret/Proofs/Invariants.lean", "WellFormed"),
}


# ---- source parsing (shared shape with doc_count_check.py) ----------------
def _block(text, start_re):
    m = re.search(start_re, text, re.M)
    if not m:
        return None
    rest = text[m.end():]
    end = re.search(r"^(deriving|inductive |structure |def |theorem |lemma |"
                    r"abbrev |namespace |end |@\[)", rest, re.M)
    return rest[: end.start()] if end else rest


def real_names(kind, path, name):
    text = (ROOT / path).read_text()
    if kind == "ctor":
        blk = _block(text, r"^inductive\s+" + re.escape(name) + r"\b")
        pat = r"^\s*\|\s*([A-Za-z_]\w*)"
    else:
        blk = _block(text, r"^structure\s+" + re.escape(name) + r"\b")
        pat = r"^  ([A-Za-z_]\w*)\s*:"
    if blk is None:
        raise SystemExit(f"cannot find {name} in {path}")
    return re.findall(pat, blk, re.M)


# ---- metadata parsing ------------------------------------------------------
def parse_metadata(defname):
    text = META.read_text()
    m = re.search(r"def\s+" + re.escape(defname) + r"\s*:.*?:=\s*\[(.*?)\]\s*\n",
                  text, re.S)
    if not m:
        raise SystemExit(f"cannot find metadata list {defname} in {META}")
    entries = []
    for block in re.findall(r"\{([^}]*)\}", m.group(1)):
        d = dict(re.findall(r'(\w+)\s*:=\s*"([^"]*)"', block))
        entries.append(d)
    return entries


def validate(defname, entries):
    kind, path, name = SOURCES[defname]
    real = real_names(kind, path, name)
    meta = [e["name"] for e in entries]
    errs = []
    if len(meta) != len(set(meta)):
        dups = sorted({n for n in meta if meta.count(n) > 1})
        errs.append(f"{defname}: duplicate metadata name(s): {dups}")
    unknown = [n for n in meta if n not in real]
    if unknown:
        errs.append(f"{defname}: metadata name(s) not a real {name} "
                    f"declaration: {unknown}")
    missing = [n for n in real if n not in meta]
    if missing:
        errs.append(f"{defname}: real {name} declaration(s) missing from "
                    f"metadata: {missing}")
    if len(meta) != len(real):
        errs.append(f"{defname}: metadata count {len(meta)} != "
                    f"real count {len(real)}")
    return real, errs


# ---- rendering -------------------------------------------------------------
HEADER = ("<!-- GENERATED by scripts/extract_model_docs.py (RFC 084). "
          "Do not edit by hand; edit Henret/Meta/Docs.lean and regenerate. -->\n")


def render_ctor_table(title, source_path, entries):
    lines = [HEADER, f"# {title}", "",
             f"Generated from `Henret/Meta/Docs.lean`, validated against "
             f"`{source_path}` ({len(entries)} constructors).", "",
             "| # | Constructor | Since | Category | Summary |",
             "|---|---|---|---|---|"]
    for i, e in enumerate(entries, 1):
        lines.append(f"| {i} | `{e['name']}` | {e['since']} | "
                     f"{e['category']} | {e['summary']} |")
    return "\n".join(lines) + "\n"


def render_field_table(entries):
    lines = [HEADER, "# WellFormed invariant fields", "",
             f"Generated from `Henret/Meta/Docs.lean`, validated against "
             f"`Henret/Proofs/Invariants.lean` ({len(entries)} fields).", "",
             "| # | Field | Group | Since | Summary |",
             "|---|---|---|---|---|"]
    for i, e in enumerate(entries, 1):
        lines.append(f"| {i} | `{e['name']}` | {e['group']} | "
                     f"{e['since']} | {e['summary']} |")
    return "\n".join(lines) + "\n"


TABLES = {
    "runtime-op-table.md":    ("runtimeOpDocs",  "RuntimeOp operation grammar",
                               "Henret/Scheduler/Op.lean"),
    "task-state-table.md":    ("taskStateDocs",  "TaskState lifecycle states",
                               "Henret/Actor/Task.lean"),
    "step-result-table.md":   ("stepResultDocs", "StepResult outcomes",
                               "Henret/Core/Result.lean"),
    "wellformed-field-table.md": ("wellFormedDocs", "WellFormed invariant fields",
                                  "Henret/Proofs/Invariants.lean"),
}


def generate():
    out = {}
    all_errs = []
    for fname, (defname, title, src) in TABLES.items():
        entries = parse_metadata(defname)
        _real, errs = validate(defname, entries)
        all_errs += errs
        if defname == "wellFormedDocs":
            out[fname] = render_field_table(entries)
        else:
            out[fname] = render_ctor_table(title, src, entries)
    if all_errs:
        for e in all_errs:
            print(f"VALIDATION FAIL: {e}")
        sys.exit(1)
    return out


def main():
    check = "--check" in sys.argv
    out = generate()
    diverged = []
    OUT.mkdir(parents=True, exist_ok=True)
    for fname, content in out.items():
        p = OUT / fname
        if check:
            cur = p.read_text() if p.exists() else ""
            if cur != content:
                diverged.append(fname)
        else:
            p.write_text(content)
    if check:
        if diverged:
            print(f"GENERATED-DOC DIVERGENCE: {diverged} differ from a fresh "
                  f"generation — run scripts/extract_model_docs.py and commit")
            sys.exit(1)
        print(f"model-docs: {len(out)} generated tables match committed files")
    else:
        print(f"model-docs: wrote {len(out)} tables to {OUT}")


if __name__ == "__main__":
    main()
