#!/usr/bin/env python3
"""RFC 084 — RFC-index generator.

Consumes the RFC 085 front-matter metadata in `rfcs/**/*.md` and emits the
RFC index, so it is not a hand-maintained list. Groups by lifecycle folder
(done / proposed / archive) per RFC 000.

    extract_rfc_index.py [--check]   ->  docs/generated/rfc-index.md

Stdlib only.
"""
import re
import sys
from pathlib import Path

ROOT = Path(".")
RFCS = ROOT / "rfcs"
OUT = ROOT / "docs/generated"

HEADER = ("<!-- GENERATED by scripts/extract_rfc_index.py (RFC 084) from RFC "
          "front matter (RFC 085). Do not edit by hand. -->\n")


def front_matter(path):
    text = path.read_text()
    m = re.match(r"---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        fm[k.strip()] = v.strip()
    return fm


def collect():
    rows = {"done": [], "proposed": [], "archive": []}
    for folder in rows:
        d = RFCS / folder
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.md")):
            fm = front_matter(p)
            if not fm:
                continue
            rows[folder].append({
                "rfc": fm.get("rfc", "?"),
                "title": fm.get("title", p.stem),
                "status": fm.get("status", "?"),
                "impl": fm.get("implemented_in", "null"),
                "category": fm.get("category", ""),
                "superseded_by": fm.get("superseded_by", "[]"),
                "path": f"{folder}/{p.name}",
            })
    for folder in rows:
        rows[folder].sort(key=lambda r: int(re.sub(r"\D", "", str(r["rfc"])) or 0))
    return rows


def generate():
    rows = collect()
    total = sum(len(v) for v in rows.values())
    out = [HEADER, "# RFC index", "",
           f"{total} RFCs: {len(rows['done'])} implemented, "
           f"{len(rows['proposed'])} proposed/in-wave, "
           f"{len(rows['archive'])} archived. Generated from RFC front matter.",
           ""]
    if rows["done"]:
        out += ["## Implemented (`done/`)", "",
                "| RFC | Title | Shipped | Category |", "|---|---|---|---|"]
        for r in rows["done"]:
            out.append(f"| [{r['rfc']}]({r['path']}) | {r['title']} | "
                       f"{r['impl']} | {r['category']} |")
        out.append("")
    if rows["proposed"]:
        out += ["## Proposed / in-wave (`proposed/`)", "",
                "| RFC | Title | Status | Category |", "|---|---|---|---|"]
        for r in rows["proposed"]:
            st = r["status"] + (f" ({r['impl']})" if r["impl"] != "null" else "")
            out.append(f"| [{r['rfc']}]({r['path']}) | {r['title']} | "
                       f"{st} | {r['category']} |")
        out.append("")
    if rows["archive"]:
        out += ["## Archived (`archive/`)", "",
                "| RFC | Title | Status | Note |", "|---|---|---|---|"]
        for r in rows["archive"]:
            note = (f"superseded by RFC {r['superseded_by'].strip('[]')}"
                    if r["status"] == "Superseded" else r["status"])
            out.append(f"| [{r['rfc']}]({r['path']}) | {r['title']} | "
                       f"{r['status']} | {note} |")
        out.append("")
    return {"rfc-index.md": "\n".join(out).rstrip() + "\n"}


def main():
    check = "--check" in sys.argv
    out = generate()
    OUT.mkdir(parents=True, exist_ok=True)
    diverged = []
    for fname, content in out.items():
        p = OUT / fname
        if check:
            cur = p.read_text() if p.exists() else ""
            if cur != content:
                diverged.append(fname)
        else:
            p.write_text(content)
    if check:
        if diverged:
            print(f"GENERATED-DOC DIVERGENCE: {diverged} differ — run "
                  f"scripts/extract_rfc_index.py and commit")
            sys.exit(1)
        print("rfc-index: generated file matches committed")
    else:
        print(f"rfc-index: wrote {len(out)} file to {OUT}")


if __name__ == "__main__":
    main()
