#!/usr/bin/env python3
"""RFC 084 — public-theorem index and axiom-budget generator.

The public-theorem source of truth (084-4) is the explicit allowlist in
`scripts/axiom_audit.py`: every name there is verified to exist and to stay
within its declared axiom budget by the strict axiom audit (gate 6), so the
allowlist doubles as the gate-validated public-theorem register. This
generator parses that allowlist (it does not import it — the audit reads
stdin at import) and emits:

    docs/src/generated/public-theorem-index.md
    docs/src/generated/axiom-budget.md

    extract_theorem_docs.py [--check]

Stdlib only.
"""
import re
import sys
from pathlib import Path

ROOT = Path(".")
AUDIT = ROOT / "scripts/axiom_audit.py"
OUT = ROOT / "docs/src/generated"

HEADER = ("<!-- GENERATED by scripts/extract_theorem_docs.py (RFC 084). "
          "Do not edit by hand; the source of truth is the allowlist in "
          "scripts/axiom_audit.py, validated by gate 6. -->\n")


def parse_audit():
    text = AUDIT.read_text()
    # Drop full-line comments so commented-out allowlist entries are not counted.
    text = "\n".join(ln for ln in text.splitlines()
                     if not ln.lstrip().startswith("#"))
    # ALLOWLIST entries: "Henret.X": (required, allowed),
    entries = []
    for m in re.finditer(
            r'"(Henret[^"]+)"\s*:\s*\(\s*([^,]+?)\s*,\s*([^)]*(?:\{[^}]*\}[^)]*)?)\)',
            text):
        name, required, allowed = m.group(1), m.group(2), m.group(3).strip()
        entries.append((name, required, allowed))
    # NATIVE_SIX axiom names
    nm = re.search(r"NATIVE_SIX\s*=\s*\{(.*?)\}", text, re.S)
    native = re.findall(r'"([^"]+)"', nm.group(1)) if nm else []
    return entries, native


def axiom_class(allowed):
    if "NATIVE" in allowed:
        return ("native", "propext, Quot.sound (+ NativeDeque FFI axioms)")
    if "STD_C" in allowed:
        return ("STD_C", "propext, Quot.sound, Classical.choice")
    return ("STD", "propext, Quot.sound")


def namespace_of(name):
    # Henret.Bridge.x -> "Henret.Bridge"; Henret.x -> "Henret"
    parts = name.split(".")
    return ".".join(parts[:-1]) if len(parts) > 2 else parts[0]


def generate():
    entries, native = parse_audit()
    if not entries:
        print("VALIDATION FAIL: no allowlist entries parsed from axiom_audit.py")
        sys.exit(1)

    # public-theorem-index.md, grouped by namespace
    groups = {}
    for name, _req, _al in entries:
        groups.setdefault(namespace_of(name), []).append(name)
    idx = [HEADER, "# Public theorem index", "",
           f"The {len(entries)} gate-audited public theorems "
           f"(source: the `ALLOWLIST` in `scripts/axiom_audit.py`, validated "
           f"by the strict axiom audit). Grouped by namespace.", ""]
    for ns in sorted(groups):
        idx.append(f"## {ns}")
        idx.append("")
        for n in sorted(groups[ns]):
            idx.append(f"- `{n}`")
        idx.append("")
    index_md = "\n".join(idx).rstrip() + "\n"

    # axiom-budget.md
    by_class = {"STD": [], "STD_C": [], "native": []}
    for name, _req, allowed in entries:
        cls, _desc = axiom_class(allowed)
        by_class[cls].append(name)
    bud = [HEADER, "# Axiom budget", "",
           f"Every one of the {len(entries)} audited public theorems depends "
           f"only on Lean's kernel axioms (`propext`, `Quot.sound`, and — for "
           f"reachability theorems using `by_cases`/`obtain` — `Classical."
           f"choice`); the optional native layer adds typed FFI axioms. No "
           f"project-specific axioms, no `native_decide`.", "",
           "## Axiom classes", "",
           "| Class | Axioms | Theorems |",
           "|---|---|---|",
           f"| STD | propext, Quot.sound | {len(by_class['STD'])} |",
           f"| STD_C | propext, Quot.sound, Classical.choice | "
           f"{len(by_class['STD_C'])} |",
           f"| native | STD(_C) + NativeDeque FFI axioms | "
           f"{len(by_class['native'])} |", ""]
    if native:
        bud.append("## Trusted native axioms (`Henret.Native`, RFC 010)")
        bud.append("")
        for a in native:
            bud.append(f"- `{a}`")
        bud.append("")
    budget_md = "\n".join(bud).rstrip() + "\n"

    return {"public-theorem-index.md": index_md, "axiom-budget.md": budget_md}


def main():
    check = "--check" in sys.argv
    out = generate()
    OUT.mkdir(parents=True, exist_ok=True)
    diverged = []
    for fname, content in out.items():
        p = OUT / fname
        if check:
            cur = p.read_text() if p.exists() else ""
            if cur != content:
                diverged.append(fname)
        else:
            p.write_text(content)
    if check:
        if diverged:
            print(f"GENERATED-DOC DIVERGENCE: {diverged} differ — run "
                  f"scripts/extract_theorem_docs.py and commit")
            sys.exit(1)
        print(f"theorem-docs: {len(out)} generated files match committed")
    else:
        print(f"theorem-docs: wrote {len(out)} files to {OUT}")


if __name__ == "__main__":
    main()
