#!/usr/bin/env python3
"""RFC 069 — Proof Dependency Budget generator.

Classifies the *audited* theorem surface (the source of truth is the allowlist in
``scripts/axiom_audit.py``, kept in sync with ``check.sh`` by gate 0) along three
dimensions, so a reader can choose lightweight imports and see exactly which
theorems carry a heavier dependency:

* **constructiveness** — does the theorem use ``Classical.choice``?
    - ``constructive`` : only ``propext`` / ``Quot.sound`` (STD)
    - ``classical``    : also ``Classical.choice`` (STD_C)
    - ``trusted``      : also declared native/FFI axioms (RFC 010 layer)
* **import weight** — which layer must be elaborated to obtain the theorem,
  derived from the theorem's namespace (a coarse but stable proxy; full
  import-graph precision is a deliberate v1 non-goal, see RFC 069).
* **stability** — ``public-stable`` if the name is on the prefix-defined public
  surface (``docs/src/generated/public-theorems.md``, RFC 062 §9.2); otherwise
  ``internal`` (an audited headline lemma that is not part of the public API).

This generator does not introspect proof terms; it joins data that already
exists (the audit allowlist + the public-theorem snapshot). The axiom-footprint
*summary counts* live in ``docs/src/generated/axiom-budget.md`` (RFC 084); this file
is the per-theorem **budget table** RFC 069 adds on top.

Usage:
    proof_dependency_budget.py            # regenerate + write the doc
    proof_dependency_budget.py --check    # regenerate + diff (gate 7); fail on drift
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "src" / "generated" / "proof-dependency-budget.md"
PUBLIC_SNAPSHOT = ROOT / "docs" / "src" / "generated" / "public-theorems.md"

HEADER = (
    "<!-- GENERATED by scripts/proof_dependency_budget.py (RFC 069). Do not edit "
    "by hand; the source of truth is the allowlist in scripts/axiom_audit.py "
    "(tier) joined with docs/src/generated/public-theorems.md (stability). A diff here "
    "means an audited theorem changed tier, namespace, or public status: "
    "regenerate with `python3 scripts/proof_dependency_budget.py` and treat a "
    "constructive\u2192classical move as a conscious budget decision. -->"
)

# Import-weight buckets, keyed by the second namespace segment of the theorem.
WEIGHT = {
    "Native": "native",      # optional FFI/Chase-Lev layer (RFC 010)
    "Bridge": "bridge",      # lean-runtime bridge / refinement machinery
    "Conformance": "conformance",  # golden conformance suite
    "Trace": "standard",     # trace projection
    "Diagnostics": "standard",     # fault taxonomy
}
CORE = "core"  # plain Henret.* — model + preservation corpus


def load_audit():
    """Exec only the data definitions of axiom_audit.py (it reads stdin at module
    level, so a plain import would block). Returns a namespace with ALLOWLIST etc."""
    src = (ROOT / "scripts" / "axiom_audit.py").read_text()
    marker = "text = sys.stdin.read()"
    head = src.split(marker, 1)[0]
    ns: dict = {}
    exec(compile(head, "axiom_audit.py", "exec"), ns)

    class _A:
        ALLOWLIST = ns["ALLOWLIST"]
        STD = ns["STD"]
        STD_C = ns["STD_C"]
    return _A


def public_stable_names() -> set[str]:
    """Bare theorem names on the prefix-defined public surface."""
    names: set[str] = set()
    if not PUBLIC_SNAPSHOT.exists():
        return names
    for line in PUBLIC_SNAPSHOT.read_text().splitlines():
        line = line.strip()
        if line.startswith("- `"):
            names.add(line.split("`")[1])
    return names


def classify(full_name: str, extra: set, allowed: set, audit) -> tuple[str, str]:
    """Return (constructiveness, import_weight) for one audited theorem."""
    if extra:  # non-empty extra axioms == declared native/FFI axioms
        constr = "trusted"
    elif "Classical.choice" in allowed:
        constr = "classical"
    else:
        constr = "constructive"
    seg = full_name.split(".")
    weight = WEIGHT.get(seg[1], CORE) if len(seg) >= 2 else CORE
    return constr, weight


def render(audit) -> str:
    stable = public_stable_names()
    rows = []
    counts = {"constructive": 0, "classical": 0, "trusted": 0}
    weights: dict[str, int] = {}
    stab_counts = {"public-stable": 0, "internal": 0}
    for full, (extra, allowed) in sorted(audit.ALLOWLIST.items()):
        constr, weight = classify(full, extra, allowed, audit)
        bare = full.split(".")[-1]
        stability = "public-stable" if bare in stable else "internal"
        footprint = "trusted-extern" if constr == "trusted" else "kernel-standard"
        rows.append((full, weight, footprint, constr, stability))
        counts[constr] += 1
        weights[weight] = weights.get(weight, 0) + 1
        stab_counts[stability] += 1

    total = len(rows)
    classical = [full for full, _, _, c, _ in rows if c == "classical"]

    out = [HEADER, "", "# Proof dependency budget", ""]
    out.append(
        f"{total} audited theorems, classified by import weight, axiom footprint, "
        "constructiveness, and public stability (RFC 069). The axiom-footprint "
        "*summary counts* are in [`axiom-budget.md`](axiom-budget.md); this file is "
        "the per-theorem budget."
    )
    out += ["", "## Summary", "",
            "| Dimension | Bucket | Theorems |", "|---|---|---|"]
    for k in ("constructive", "classical", "trusted"):
        out.append(f"| constructiveness | {k} | {counts[k]} |")
    for k in sorted(weights):
        out.append(f"| import weight | {k} | {weights[k]} |")
    for k in ("public-stable", "internal"):
        out.append(f"| stability | {k} | {stab_counts[k]} |")

    out += ["", "## Classical-reasoning budget", "",
            f"{len(classical)} audited theorems depend on `Classical.choice` "
            "(reachability theorems reached via `by_cases` / `obtain`). Every one is "
            "listed so a move from `constructive` to `classical` is a visible, "
            "reviewable change:", ""]
    for full in classical:
        out.append(f"- `{full}`")

    out += ["", "## Per-theorem budget", "",
            "| Theorem | Import weight | Axiom footprint | Constructiveness | Stability |",
            "|---|---|---|---|---|"]
    for full, weight, footprint, constr, stability in rows:
        out.append(f"| `{full}` | {weight} | {footprint} | {constr} | {stability} |")
    out.append("")
    return "\n".join(out)


def main() -> int:
    audit = load_audit()
    content = render(audit)
    check = "--check" in sys.argv
    if check:
        if not OUT.exists():
            print(f"proof-dependency-budget: {OUT} missing; run without --check", file=sys.stderr)
            return 1
        if OUT.read_text() != content:
            print("proof-dependency-budget: DRIFT — regenerate with "
                  "`python3 scripts/proof_dependency_budget.py`", file=sys.stderr)
            return 1
        n = content.count("\n| `Henret")
        print(f"proof-dependency-budget: {n} audited theorems, snapshot current")
        return 0
    OUT.write_text(content)
    print(f"proof-dependency-budget: wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
