#!/usr/bin/env python3
"""RFC 062 §9.2 — public-theorem name diff gate.

Protects the *prefix-defined* public theorem surface against accidental
rename/removal during proof refactoring. This complements
``extract_theorem_docs.py`` (which snapshots the strict axiom-audit allowlist):
the per-operation preservation/projection theorems are not all individually
audited, so a refactor could rename ``preserves_wf_sleep`` with no gate firing.

The public surface is defined mechanically as every top-level ``theorem`` in
``Henret/`` whose name begins with one of the stable public prefixes:

    preserves_wf_   step_preserves_   reachable_   bridge_   run_preserves_

Each name is classified by prefix, and cross-referenced against the audit
allowlist (``scripts/axiom_audit.py``) to mark which are also axiom-audited.
The committed snapshot is ``docs/src/generated/public-theorems.md``.

    public_theorem_index.py            # regenerate the snapshot
    public_theorem_index.py --check    # regenerate + diff (gate 7); fail on drift

A public name therefore cannot disappear or be renamed without a conscious edit
to the snapshot — that edit is the migration record (see
``docs/src/proof-api-stability.md``). Internal helper names (``wf_*_pass`` etc.) are
deliberately *not* in this surface and may change freely. Stdlib only.
"""
import re
import sys
from pathlib import Path

ROOT = Path(".")
SRC = ROOT / "Henret"
AUDIT = ROOT / "scripts/axiom_audit.py"
OUT = ROOT / "docs/src/generated/public-theorems.md"

# Stable public-theorem name prefixes (proof-style.md §7). Order = display order.
PREFIXES = [
    ("preserves_wf_", "preservation"),
    ("step_preserves_", "projection"),
    ("reachable_", "reachability"),
    ("bridge_", "bridge"),
    ("run_preserves_", "run"),
]

HEADER = (
    "<!-- GENERATED by scripts/public_theorem_index.py (RFC 062 §9.2). "
    "Do not edit by hand. This is the committed snapshot of the prefix-defined "
    "public theorem surface; the source of truth is the `^theorem` declarations "
    "in Henret/. A diff here means a public theorem was added, renamed, or "
    "removed: regenerate with `python3 scripts/public_theorem_index.py` and, for "
    "a removal/rename, record the migration in docs/src/proof-api-stability.md. -->\n"
)

THEOREM_RE = re.compile(r"^theorem\s+([A-Za-z0-9_]+)", re.M)


def audited_names() -> set[str]:
    """Bare names present in the axiom-audit allowlist (prefix-stripped)."""
    text = AUDIT.read_text()
    text = "\n".join(ln for ln in text.splitlines()
                     if not ln.lstrip().startswith("#"))
    names = set()
    for m in re.finditer(r'"(Henret[^"]+)"\s*:', text):
        full = m.group(1)
        bare = full.split(".")[-1]
        names.add(bare)
    return names


def collect() -> dict[str, str]:
    """Map public theorem name -> category, scanning all of Henret/."""
    found: dict[str, str] = {}
    for p in sorted(SRC.rglob("*.lean")):
        for name in THEOREM_RE.findall(p.read_text()):
            for prefix, category in PREFIXES:
                if name.startswith(prefix):
                    found[name] = category
                    break
    return found


def render(found: dict[str, str], audited: set[str]) -> str:
    by_cat: dict[str, list[str]] = {cat: [] for _, cat in PREFIXES}
    for name, cat in found.items():
        by_cat[cat].append(name)
    lines = [HEADER, "# Public theorem surface (prefix-defined)\n"]
    total = len(found)
    n_audited = sum(1 for n in found if n in audited)
    lines.append(
        f"{total} public theorems across {len(by_cat)} categories; "
        f"{n_audited} also axiom-audited (`scripts/axiom_audit.py`).\n")
    for _, cat in PREFIXES:
        names = sorted(by_cat[cat])
        lines.append(f"\n## {cat} ({len(names)})\n")
        for name in names:
            mark = " *(audited)*" if name in audited else ""
            lines.append(f"- `{name}`{mark}")
    return "\n".join(lines) + "\n"


def main() -> None:
    check = "--check" in sys.argv
    if not SRC.exists():
        print(f"FAIL: {SRC} not found (run from repo root)")
        sys.exit(1)
    found = collect()
    audited = audited_names()
    content = HEADER + render(found, audited)[len(HEADER):]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    if check:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur != content:
            print("PUBLIC-THEOREM DIVERGENCE: docs/src/generated/public-theorems.md "
                  "is stale — a public theorem was added, renamed, or removed.")
            print("  Run: python3 scripts/public_theorem_index.py")
            print("  For a rename/removal, record it in docs/src/proof-api-stability.md.")
            sys.exit(1)
        print(f"public-theorem index: {len(found)} names, snapshot current")
    else:
        OUT.write_text(content)
        print(f"public-theorem index: wrote {len(found)} names to {OUT}")


if __name__ == "__main__":
    main()
